name: Build and Publish NuGet Packages

on:
  push:
    branches:
      - master
permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Major: '1'
      Minor: '0'
      Version: '${{ github.run_number }}'
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
        ports:
          - 2375:2375
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ensure Docker is running
        run: |
          docker version
          docker info

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Restore dependencies
        run: dotnet restore --no-cache --force-evaluate

      - name: Build solution
        run: dotnet build Messaging.sln --configuration Release --no-restore

      - name: Run tests
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: dotnet test Messaging.sln --configuration Release --no-build --no-restore

      - name: Pack NuGet packages
        run: dotnet pack Messaging.sln --configuration Release --no-build --output ./packages /p:Version=${{ env.Major }}.${{ env.Minor }}.${{ env.Version }}

      - name: Push NuGet packages
        run: dotnet nuget push "packages/*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ github.token }} --skip-duplicate